//
// Created by admin on 7/17/2017.
//

#ifndef DIPOLE_GENERATOR_CPP_BULKSUPERCELLGENERATOR_HPP
#define DIPOLE_GENERATOR_CPP_BULKSUPERCELLGENERATOR_HPP


class BulkSupercellGenerator {
private:

public:

};


#endif //DIPOLE_GENERATOR_CPP_BULKSUPERCELLGENERATOR_HPP
